apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
    {{- with .Values.deployment.selection_labels }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
      {{- with .Values.deployment.selection_labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled}}
      serviceAccountName: {{.Values.serviceAccount.name}}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          env:
          {{- toYaml .Values.deployment.env | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP