{{- if .Values.serviceAccount.pullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.pullSecret.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{- end}}