apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- with .Values.deployment.selection_labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080