{{- if .Values.serviceAccount.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- if .Values.serviceAccount.pullSecret.enabled }}
imagePullSecrets:
  - name: {{ .Values.serviceAccount.pullSecret.secretName }}
  {{- end}}
  {{- end}}


