# This is a basic workflow to help you get started with Actions

name: Helm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@master
      - uses: actions/upload-artifact@master
        with:
          name: chart
          path: deploy/helm/
      - name: Archive using zip or tar
        uses: NSCoder/archive-action@v1.0.0
        with:
          #args: "tar czvf chart.tar.gz --transform 's,^deploy/helm,,' deploy/helm/*"
          args: ls deploy/helm
